#!/bin/tcsh
#PBS -N gitData
#PBS -l nodes=1:vortex:ppn=12
#PBS -l walltime=24:00:00
#PBS -j oe
#PBS -o /sciclone/geounder/dev/geoBoundaries/scripts/geoBoundaryBot/external/AuthData/jobFiles

source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load python/usermodules
module load git/2.42.0
module load git-lfs

unsetenv PYTHONPATH

conda activate gbAuth
cd /sciclone/geounder/dev/geoBoundaries/scripts/geoBoundaryBot/external/AuthData
python gitData.py vortex >& gitData.out